// scripts/scheduledReports.js
// Run via: node scripts/scheduledReports.js
// Or add to package.json: "report:scheduled": "node scripts/scheduledReports.js"
// For production, use node-cron or a system cron to invoke this monthly.
//
// Install deps if not present: npm install node-cron nodemailer --save

require('dotenv').config();
const mongoose = require('mongoose');
const cron = require('node-cron');
const nodemailer = require('nodemailer');
const accountingService = require('../services/accountingService');

const MONGO_URI = process.env.MONGODB_URI || process.env.MONGO_URI;
const FINANCE_EMAIL_LIST = (process.env.FINANCE_REPORT_EMAILS || '').split(',').filter(Boolean);
const SMTP_HOST = process.env.SMTP_HOST;
const SMTP_PORT = Number(process.env.SMTP_PORT || 587);
const SMTP_USER = process.env.SMTP_USER;
const SMTP_PASS = process.env.SMTP_PASS;
const FROM_EMAIL = process.env.FROM_EMAIL || 'noreply@gratoengineering.com';

function getLastMonthRange() {
  const now = new Date();
  const year  = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear();
  const month = now.getMonth() === 0 ? 12 : now.getMonth();
  const start = new Date(year, month - 1, 1);
  const end   = new Date(year, month, 0);   // last day of last month
  return {
    startDate: start.toISOString().slice(0, 10),
    endDate:   end.toISOString().slice(0, 10),
    label:     `${start.toLocaleString('default', { month: 'long' })} ${year}`
  };
}

async function buildEmailContent(range) {
  const [tbCsv, jeCsv, plCsv, bsCsv, kpis] = await Promise.all([
    accountingService.exportTrialBalanceCSV(range),
    accountingService.exportJournalEntriesCSV(range),
    accountingService.exportProfitAndLossCSV(range),
    accountingService.exportBalanceSheetCSV({ asOfDate: range.endDate }),
    accountingService.getDashboardKPIs()
  ]);

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 650px; margin: 0 auto; padding: 20px;">
      <h2 style="color: #1a3c5e;">Monthly Finance Report — ${range.label}</h2>
      <p>Please find this month's accounting reports attached.</p>

      <table style="width:100%; border-collapse:collapse; margin:20px 0;">
        <tr style="background:#f5f5f5;">
          <th style="padding:10px; text-align:left; border-bottom:2px solid #ddd;">Metric</th>
          <th style="padding:10px; text-align:right; border-bottom:2px solid #ddd;">Value</th>
        </tr>
        ${[
          ['Cash Balance',         kpis.cashBalance],
          ['Total Receivables',    kpis.totalReceivables],
          ['Total Payables',       kpis.totalPayables],
          [`Revenue (${range.label})`, kpis.revenueThisMonth],
          [`Expenses (${range.label})`, kpis.expensesThisMonth],
          [kpis.isProfit ? 'Net Profit' : 'Net Loss', Math.abs(kpis.netProfitThisMonth)],
          ['Overdue Invoices',     kpis.overdueInvoices],
          ['Pending Journals',     kpis.pendingJournals]
        ].map(([label, value]) => `
          <tr>
            <td style="padding:8px 10px; border-bottom:1px solid #eee;">${label}</td>
            <td style="padding:8px 10px; border-bottom:1px solid #eee; text-align:right; font-weight:bold;">${
              typeof value === 'number' && label.includes('Invoice') || label.includes('Journal')
                ? value
                : Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })
            }</td>
          </tr>
        `).join('')}
      </table>

      <p style="color:#888; font-size:12px;">
        This report was auto-generated by the Finance Accounting System on ${new Date().toLocaleString()}.
        Four CSV files are attached: Trial Balance, Journal Entries, P&amp;L, Balance Sheet.
      </p>
    </div>
  `;

  return { html, attachments: [
    { filename: `trial-balance-${range.label}.csv`,    content: tbCsv },
    { filename: `journal-entries-${range.label}.csv`,  content: jeCsv },
    { filename: `profit-and-loss-${range.label}.csv`,  content: plCsv },
    { filename: `balance-sheet-${range.label}.csv`,    content: bsCsv }
  ]};
}

async function sendMonthlyReports() {
  if (!FINANCE_EMAIL_LIST.length) {
    console.warn('No recipients in FINANCE_REPORT_EMAILS — skipping email send');
    return;
  }

  const transporter = nodemailer.createTransporter({
    host: SMTP_HOST, port: SMTP_PORT, secure: SMTP_PORT === 465,
    auth: { user: SMTP_USER, pass: SMTP_PASS }
  });

  const range = getLastMonthRange();
  console.log(`Generating monthly reports for ${range.label}…`);

  const { html, attachments } = await buildEmailContent(range);

  await transporter.sendMail({
    from: `Finance System <${FROM_EMAIL}>`,
    to: FINANCE_EMAIL_LIST.join(', '),
    subject: `Monthly Finance Report — ${range.label}`,
    html,
    attachments
  });

  console.log(`✅ Monthly report sent to: ${FINANCE_EMAIL_LIST.join(', ')}`);
}

async function run() {
  if (!MONGO_URI) throw new Error('MONGO_URI not set');
  await mongoose.connect(MONGO_URI);
  console.log('Connected to DB');

  // Run immediately if called directly (e.g. for testing)
  if (process.argv.includes('--now')) {
    await sendMonthlyReports();
    await mongoose.disconnect();
    process.exit(0);
  }

  // Otherwise schedule: 7am on 1st of every month
  cron.schedule('0 7 1 * *', async () => {
    console.log('Running scheduled monthly report…');
    try {
      await sendMonthlyReports();
    } catch (err) {
      console.error('Scheduled report failed:', err.message);
    }
  });

  console.log('Scheduler running. Reports will send on the 1st of each month at 07:00.');
}

run().catch(err => {
  console.error('Fatal:', err.message);
  process.exit(1);
});